# Generated by Django 5.0.7 on 2024-08-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pictures/'),
        ),
    ]
