# Generated by Django 5.0.7 on 2024-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='word_count',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
