# Generated by Django 5.0.7 on 2024-08-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
